# =============================================================================
# ANSIBLE INVENTORY - Hajar Project
# =============================================================================

all:
  children:
    zeppelin:
      hosts:
        zeppelin-server:
          ansible_host: "3.65.219.232"
    
    spark:
      hosts:
        spark-server:
          ansible_host: "10.10.11.6"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/hajar-project-key.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@3.65.219.232"'
    
    neo4j:
      hosts:
        neo4j-server:
          ansible_host: "10.10.11.13"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/hajar-project-key.pem -W %h:%p -o StrictHostKeyChecking=no ubuntu@3.65.219.232"'
    
    private:
      children:
        spark:
        neo4j:
    
    compute:
      children:
        zeppelin:
        spark:
        neo4j:

  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
